### ISSUE TITLE
Inquiry about further Wavebird Applications

### ISSUE THREAD

**Issue by dolega** [CFSworks/wavebird-reversing#3]
Hi! I just wanted to say thank you so much for your writeup, it's great to read and see an application closer to my interests on a topic I've only scratched the surface of.

I wanted to ask a couple of questions, mainly if it would be possible to take the information a step further and create a Wavebird receiver out of a 2.4GHz radio receiver (the NFR24L01, since the HackRF One is on the more expensive side) and some Arduino code to take the incoming signal and process it. The thought came from seeing Wavebirds on eBay go for so much as a complete kit since many people lose the receiver but not the controller.

However, I've been having trouble with getting them to operate on the same frequency. Do you have any experience working with something like this, and would you have any advice? Do you thing something like this is feasible?

Thanks again!

**Comment by CFSworks** [comment]
Hi there!

You're actually not the first person to ask about this, and someone [has succeeded in building their own receiver](https://twitter.com/webhdx/status/1463213222908121093) recently. I'm not really sure how much more progress they've made since then since I haven't been following it closely, but I could pass along your contact info to them if you'd like?

Cheers,
Sam

**Comment by dolega** [comment]
Oh wow, of course it'd be them haha, they've been making great strides in the GC modding community with PicoBoot and I'm not sure if they'd want to share their current info on it, but if you'd be able to pass contact info that'd be great! 

Just looking at the idea as something to learn from and not for distributing, and if they can provide any guidance on what components they've used and how they went about it, I'd greatly appreciate it. Thanks!
