### ISSUE TITLE
Color uncertainty in explanation of graphs in chapter 5.

### ISSUE THREAD

**Issue by scottnm** [CFSworks/wavebird-reversing#4]
In the ["A closer look at the wave bird's line code"](https://github.com/CFSworks/wavebird-reversing/tree/master/05_line_coding_and_framing#a-closer-look-at-the-wavebirds-line-code) section of Ch5, there's a description which references reds/greens

![image](https://github.com/CFSworks/wavebird-reversing/assets/5483270/e1a1ed39-d6ad-40ff-a8c0-210949e6e07c)

> These are probably our 0s and 1s. We can't really do much besides guess here, but let's arbitrarily call the green one '1' (because the plateau at the very end is high) and the red one '0'. If we're wrong we can come back and change it.

---

Are "green" and "red" supposed to refer to colors in either of those two graphics? the first one is blue and the second two are both green but nothing is red? I'm not really sure what "red" refers to.  I may be totally misreading what this section is trying to convey (disclaimer: I'm a total beginner to all of this radio stuff and even ignoring the color stuff I'm sort of struggling to see the pattern between the blue and green graphs which probably isn't helping)

can you help clarify for me?

**Comment by CFSworks** [comment]
Haha, oh man! Looks like my [deuteranopia](https://en.wikipedia.org/wiki/Color_blindness#Deuteranopia) got the better of me. Red and green, though distinct to me, don't look *that* different, so probably I was intending to change one of the figures to be red later, then missed it when proof-reading.

The lower figure is supposed to be drawn with a red line, not a green one. I'll push a fix for this.

Thanks for reaching out (and for reading)!

**Comment by scottnm** [comment]
Of course! Thanks for putting together this awesome resource. It's been really helpful and approachable!
